import "@/styles/globals.css";

import type { Metadata } from "next";
import { AppProvider, ApiProvider } from "./providers";
import { cn } from "@/lib/utils";
import fonts from "@/assets/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={cn(fonts.sansFont.variable)} suppressHydrationWarning>
      <body>
        <ApiProvider
          config={{
            baseURL: process.env.SERVER_URL
          }}
        >
          <AppProvider>{children}</AppProvider>
        </ApiProvider>
      </body>
    </html>
  );
}
